name: Benchmark

on:
  push:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-slim

    strategy:
      fail-fast: false
      matrix:
        seed: [1]
        frames: [100]
        width: [2000]
        height: [2000]
        obstacles: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400]

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libcgal-dev \
            libgmp-dev \
            libmpfr-dev \
            python3 \
            python3-pip

          pip3 install matplotlib numpy pandas

      - name: Configure
        run: |
          rm -rf build
          cmake -B build -S .

      - name: Build
        run: cmake --build build -j

      - name: Run program
        run: |
          taskset -c 0 ./build/pathfinder \
          ${{ matrix.seed }} \
          ${{ matrix.frames }} \
          ${{ matrix.width }} \
          ${{ matrix.height }} \
          ${{ matrix.obstacles }} \
          10 10 30

      - name: Run summary
        run: python3 scripts/summary.py

      - name: Plot results
        run: python3 scripts/plot.py

      - name: Generate gif
        run: python3 scripts/gif.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: result-s${{ matrix.seed }}-w${{ matrix.width }}-h${{ matrix.height }}-o${{ matrix.obstacles }}
          path: |
            results.png
            output/_results.csv
            output/_summary.csv
            output/animation.gif